server {
    listen 1025;
    listen 1026;
    server_name localhost;

    root EngineX/www;
    index index.htm;

    client_max_body_size 2k;

    location / {
        autoindex on;
        limit_except GET POST HEAD;
        cgi_pass .py python3;
    }

    location /empty_dir {
        autoindex off;
        limit_except GET;
    }

    location /old-page {
        return 301 /new-page;
    }

    location /temp-page {
        return 302 /index.htm;
    }

    location /ext-redirect {
        return 301 http://example.com;
    }

    location /directory/Yeah/ {
        index youpi.bad_extension;
        limit_except GET;
    }

    location /upload {
        limit_except POST DELETE;
        client_max_body_size 2048b;
    }

    location /get-only {
        limit_except GET;
    }

    location /post-only {
        limit_except POST;
    }

    location /autoindex-dir {
        autoindex on;
        limit_except GET;
    }

    location /no-index-dir {
        autoindex off;
        limit_except GET;
    }

    location /mapped {
        root EngineX/www/root-Test;
        index index.htm;
        limit_except GET;
    }

    location /dir-with-index {
        root EngineX/www;
        index index.htm;
        limit_except GET;
    }

    location /cgi-bin {
        cgi_pass .py python3;
        limit_except GET POST;
    }
}


server {
    listen 1027;
    server_name localhost;

    root EngineX/www-subject-tester;
    index index.htm;

    location / {
        root EngineX/www-subject-tester;
        index index.htm;
        autoindex on;

        cgi_pass .bla EngineX/www-subject-tester/cgi_tester;

        limit_except GET DELETE;
    }

    location /directory/Yeah/ {
        index youpi.bad_extension;
        limit_except GET;
    }

    location /post_body {
        client_max_body_size 100b;
        limit_except POST;
    }

    location /directory/ {
        autoindex on;
        limit_except GET POST DELETE;
    }

    location /directory_get/ {
        root EngineX/www-subject-tester/YoupiBanane;
        index youpi.bad_extension;
        limit_except GET;
    }

    location /directory_post/ {
        cgi_pass .bla EngineX/www-subject-tester/cgi_tester;
        limit_except POST;
    }
}