server {
    listen 1025;
	# listen 1026;
	server_name localhost;
	root EngineX/www;
	index index.htm;
	
	client_max_body_size 2k;
	# cgi_timeout 5;
	# keep_alive_timeout 20;
	# client_read_timeout 600;

	location / {
		autoindex on;
		limit_except GET;
		# client_body_in_file_only on;
	}

	location / {
        cgi_pass .py python3;
    }
	location /upload{
		limit_except POST DELETE;
		client_max_body_size 1024b;
		# client_body_in_file_only on;
		# delete_files on;
	}
	location /get-only {
		limit_except GET;
	}
	location /post-only {
		limit_except POST;
	}
	location /old-page {
       return 301 /new-page;
    }
	location /temp-page {
		return 302 /index.htm;
	}
	location /ext-redirect {
		return 301 http://example.com;
	}

	location /autoindex-dir {
		autoindex  on;
	}
	
	location /no-index-dir {
		autoindex  off;
	}

	location /auto-with-index {
		autoindex  on;
		index      index.htm;
	}

	location /mapped {
		root EngineX/www/root-Test;
    	index index.htm;
	}
	location /dir-with-index { 
		root EngineX/www;
		index index.htm;
	}
	location /cgi-bin {
		cgi_pass .py python3;
		limit_except POST GET;
	}

}

server {
	listen 1027;
	server_name localhost;
	# limit_except GET;
	root EngineX/www-subject-tester;
	index index.htm;
	# autoindex on;
	# cgi_timeout 20;
	# keep_alive_timeout 20;
	# client_read_timeout 5;

    location / {
	autoindex on;
    root EngineX/www-subject-tester;
    index index.htm;

    limit_except GET POST DELETE;
    }

    location /directory/Yeah/ {
		index youpi.bad_extension;
	}

	location /post_body {
		# client_body_in_file_only on;
		client_max_body_size 100b;
		limit_except POST;
	}

	location /directory/ {
		autoindex on;
		# method_redirect POST /directory_post/;
		# method_redirect GET /directory_get/;
	}

	location /directory_get/ {
		root EngineX/www-subject-tester/YoupiBanane;
		index youpi.bad_extension;
		limit_except GET;
	}

	location /directory_post/ {
		cgi_pass .bla EngineX/www-subject-tester/cgi_tester;
		limit_except POST;
	}
}

# types {
# 	text/html       html htm shtml;
# 	text/css        css;
# 	text/plain      txt;
# 	image/jpeg      jpeg jpg;
# 	image/png       png;
# 	image/gif       gif;
# 	application/javascript   js;
# 	application/octet-stream bin exe dll;
# 	application/json 	 json;
# }
