server {
    listen 3334;
    server_name localhost;

    root www;
    index index.html;

    #################################################
    # Default Route
    #################################################

    location / {
        root www;
        index index.html;
        autoindex off;

        limit_except GET;
    }

    #################################################
    # Autoindex
    #################################################

    location /images {
        root www/images;
        autoindex on;

        limit_except GET;
    }

    #################################################
    # Upload
    #################################################

    location /upload {
        root www/upload;
        autoindex off;

        limit_except GET POST DELETE;
    }

    #################################################
    # Redirect
    #################################################

    location /old {
        return 301 /;
    }

    #################################################
    # Error Pages
    #################################################

    error_page 400 /error_pages/400.html;
    error_page 403 /error_pages/403.html;
    error_page 404 /error_pages/404.html;
    error_page 405 /error_pages/405.html;
    error_page 500 502 503 504 /error_pages/50x.html;

    location /error_pages {
        root www;
        internal;
    }
}