server {
    listen 3334;
    server_name localhost;

    root www;

    index index.html;

    location / {
        root www;
        autoindex off;
        limit_except GET;
    }

    location /images {
        root www/images;
        autoindex on;
    }

    location /upload {
        root www/upload;
        autoindex off;
    }
}

