server {
    listen 1027;
    listen 1029;

    server_name massar;

    root www;
    index index.html;

    location / {
        root www;
        index index.html;

        limit_except GET POST DELETE;
    }

    location /upload {
        root www;
        autoindex on;

        limit_except GET POST DELETE;
    }

    location /cgi-bin {
        root www/cgi-bin;

        cgi_pass .php /usr/bin/php-cgi;
        cgi_pass .py /usr/bin/python3;

        limit_except GET POST;
    }

    location /readonly {
        root www;
        autoindex on;

        limit_except GET;
    }

    # Readable directory without index.
    # Autoindex disabled => 403 Forbidden.
    location /empty_dir {
        autoindex off;

        limit_except GET;
    }

    location /error_pages {
        root www;
        internal;
    }

    error_page 400 /error_pages/400.html;
    error_page 404 /error_pages/404.html;
    error_page 405 /error_pages/405.html;
    error_page 500 502 503 504 /error_pages/50x.html;
}


server {
    listen 1028;

    server_name localhost;

    root www;
    index index.html;

    location / {
        root www;
        index index.html;

        limit_except GET POST DELETE;
    }

    location /upload {
        root www;
        autoindex on;

        limit_except GET POST DELETE;
    }

    location /cgi-bin {
        root www/cgi-bin;

        cgi_pass .php /usr/bin/php-cgi;
        cgi_pass .py /usr/bin/python3;

        limit_except GET POST;
    }

    location /readonly {
        root www;
        autoindex on;

        limit_except GET;
    }

    # Readable directory without index.
    # Autoindex disabled => 403 Forbidden.
    location /empty_dir {
        autoindex off;

        limit_except GET;
    }

    location /error_pages {
        root www;
        internal;
    }

    error_page 400 /error_pages/400.html;
    error_page 404 /error_pages/404.html;
    error_page 405 /error_pages/405.html;
    error_page 500 502 503 504 /error_pages/50x.html;
}