
server {
    listen 127.0.0.1:1027;
    server_name default_server;
    
    root ./www/html;
    index index.html;
    client_max_body_size 10M;

    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;

    location / {
        limit_except GET;
        autoindex on;
    }

    # Upload route: Tests POST, saving files, and the DELETE method
    location /upload {
        limit_except GET POST DELETE;
        allow_upload on;
        allow_delete on;
        upload_store ./www/tmp;
        upload_path ./www/uploads;
    }

    # CGI route: Tests execution based on file extension
    location /cgi-bin {
        limit_except GET POST;
        cgi_pass .php /usr/bin/php-cgi;
        cgi_pass .py /usr/bin/python3;
    }

    # Redirect route: Tests 301 Moved Permanently logic
    location /old-page {
        return 301 http://127.0.0.1:3334/;
    }
    
    # Internal route test
    location /hidden {
        internal;
    }
}

# Tests that your server checks the HTTP 'Host' header.
# SERVER 2: Virtual Host Test (Same Port, Different server_name)

server {
    listen 127.0.0.1:3334;
    server_name fake_google.com;
    
    root ./www/fake_google;
    index index.html;
    client_max_body_size 5M;

    location / {
        limit_except GET;
        autoindex off;
    }
}

# SERVER 3: Different Port for multiple port
server {
    listen 127.0.0.1:8083;
    server_name limited_server;
    
    root ./www/limited;
    index index.html;
    
    # Very small body size to easily test '413 '
    client_max_body_size 100;

    # '405 Method Not Allowed' for Get request
    location / {
        limit_except POST;
    }
}