
server {
    listen 127.0.0.1:3334;
    server_name default_server;
    
    root www;
    index index.html;
    client_max_body_size 10M;

    
    
    error_page 400 /error_pages/400.html;
    error_page 401 /error_pages/401.html;
    error_page 403 /error_pages/403.html;
    error_page 404 /error_pages/404.html;
    error_page 405 /error_pages/405.html;
    error_page 408 /error_pages/408.html;
    error_page 409 /error_pages/409.html;
    error_page 411 /error_pages/411.html;
    error_page 413 /error_pages/413.html;
    error_page 500 /error_pages/500.html;
    error_page 501 /error_pages/501.html;
    error_page 502 /error_pages/502.html;
    error_page 504 /error_pages/504.html;
    error_page 505 /error_pages/505.html;

    location / {
        limit_except GET;
        autoindex on;
    }

    # Upload route: Tests POST, saving files, and the DELETE method
    location /upload {
        limit_except GET POST DELETE;
        allow_upload on;
        allow_delete on;
        upload_store ./www/tmp;
        upload_path ./www/uploads;
    }

    # CGI route: Tests execution based on file extension
    location /cgi-bin {
        limit_except GET POST;
        cgi_pass .php /usr/bin/php-cgi;
        cgi_pass .py /usr/bin/python3;
    }

    # Redirect route: Tests 301 Moved Permanently logic
    location /old-page {
        return 301 http://127.0.0.1:3334/;
    }
    
    # Internal route test
    location /hidden {
        internal;
    }
}

# Tests that your server checks the HTTP 'Host' header.
# SERVER 2: Virtual Host Test (Same Port, Different server_name)

server {
    listen 127.0.0.1:3334;
    server_name fake_google.com;
    
    root ./www/fake_google;
    index index.html;
    client_max_body_size 5M;

    location / {
        limit_except GET;
        autoindex off;
    }
}

# SERVER 3: Different Port for multiple port
server {
    listen 127.0.0.1:8081;
    server_name limited_server;
    
    root ./www/limited;
    index index.html;
    
    # Very small body size to easily test '413 '
    client_max_body_size 100;

    # '405 Method Not Allowed' for Get request
    location / {
        limit_except POST;
    }
}