/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   handleRequest.cpp                                  :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: iel-asef <iel-asef@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/04/17 13:44:30 by iel-asef          #+#    #+#             */
/*                                                                            */
/* ************************************************************************** */

#include "../../webserv.hpp"
#include <set>

/*
 * ============================================================
 * SESSION MANAGEMENT
 * ============================================================
 */

static std::set<std::string> g_validSessions;


/*
 * HTTP header names are case-insensitive.
 */
static bool getHeaderValue(const HttpRequest& req,
                           const std::string& wanted,
                           std::string& value)
{
    std::string target = wanted;

    for (size_t i = 0; i < target.size(); ++i)
    {
        target[i] = static_cast<char>(
            std::tolower(
                static_cast<unsigned char>(target[i])
            )
        );
    }

    for (std::map<std::string, std::string>::const_iterator it =
             req.headers.begin();
         it != req.headers.end();
         ++it)
    {
        std::string name = it->first;

        for (size_t i = 0; i < name.size(); ++i)
        {
            name[i] = static_cast<char>(
                std::tolower(
                    static_cast<unsigned char>(name[i])
                )
            );
        }

        if (name == target)
        {
            value = it->second;
            return true;
        }
    }

    return false;
}


static std::string trimSessionValue(const std::string& str)
{
    size_t begin = 0;

    while (begin < str.size() &&
           (str[begin] == ' ' ||
            str[begin] == '\t'))
    {
        ++begin;
    }

    size_t end = str.size();

    while (end > begin &&
           (str[end - 1] == ' ' ||
            str[end - 1] == '\t'))
    {
        --end;
    }

    return str.substr(begin, end - begin);
}


/*
 * Extract SESSIONID from Cookie.
 */
static bool extractSessionId(const HttpRequest& req,
                             std::string& sessionId)
{
    std::string cookie;

    if (!getHeaderValue(req, "Cookie", cookie))
        return false;

    size_t start = 0;

    while (start < cookie.size())
    {
        size_t end = cookie.find(';', start);

        std::string part;

        if (end == std::string::npos)
            part = cookie.substr(start);
        else
            part = cookie.substr(start, end - start);

        part = trimSessionValue(part);

        size_t equal = part.find('=');

        if (equal != std::string::npos)
        {
            std::string name =
                trimSessionValue(part.substr(0, equal));

            std::string value =
                trimSessionValue(part.substr(equal + 1));

            if (name == "SESSIONID")
            {
                if (value.empty())
                    return false;

                sessionId = value;
                return true;
            }
        }

        if (end == std::string::npos)
            break;

        start = end + 1;
    }

    return false;
}


/*
 * Session valid only if generated by this webserv.
 */
static bool hasValidSessionCookie(const HttpRequest& req)
{
    std::string sessionId;

    if (!extractSessionId(req, sessionId))
        return false;

    return g_validSessions.find(sessionId)
        != g_validSessions.end();
}


/*
 * Generate unique session ID.
 */
static std::string generateSessionId()
{
    static unsigned long counter = 0;

    std::string id;

    do
    {
        struct timeval tv;

        gettimeofday(&tv, NULL);

        std::ostringstream out;

        out << tv.tv_sec
            << tv.tv_usec
            << getpid()
            << counter++;

        id = out.str();
    }
    while (g_validSessions.find(id)
           != g_validSessions.end());

    return id;
}


/*
 * Missing or invalid session:
 * generate new Set-Cookie.
 */
static std::string attachSessionCookie(
    const HttpRequest& req,
    const std::string& response)
{
    if (hasValidSessionCookie(req))
        return response;

    size_t headerEnd =
        response.find("\r\n\r\n");

    if (headerEnd == std::string::npos)
        return response;

    std::string sessionId =
        generateSessionId();

    g_validSessions.insert(sessionId);

    std::string cookieHeader =
        "Set-Cookie: SESSIONID="
        + sessionId
        + "; Path=/; Max-Age=3600; HttpOnly";

    return response.substr(0, headerEnd)
        + "\r\n"
        + cookieHeader
        + response.substr(headerEnd);
}


/*
 * ============================================================
 * PATH SECURITY
 * ============================================================
 */

bool isInsideRoot(const std::string& path,
                  const std::string& root)
{
    char realRoot[PATH_MAX];
    char realPath[PATH_MAX];

    if (!realpath(root.c_str(), realRoot))
        return false;

    if (realpath(path.c_str(), realPath))
    {
        std::string p(realPath);
        std::string r(realRoot);

        if (!r.empty() &&
            r[r.length() - 1] != '/')
        {
            r += "/";
        }

        return (
            p == realRoot ||
            p.find(r) == 0
        );
    }

    /*
     * Target does not exist:
     * check parent.
     */
    size_t lastSlash =
        path.rfind('/');

    if (lastSlash == std::string::npos)
        return false;

    std::string parentDir =
        path.substr(0, lastSlash);

    if (parentDir.empty())
        parentDir = "/";

    if (realpath(parentDir.c_str(), realPath))
    {
        std::string p(realPath);
        std::string r(realRoot);

        if (!r.empty() &&
            r[r.length() - 1] != '/')
        {
            r += "/";
        }

        return (
            p == realRoot ||
            p.find(r) == 0
        );
    }

    return false;
}


/*
 * ============================================================
 * DELETE
 * ============================================================
 */

std::string handleDELETE(const HttpRequest& req,
                         const ServerConfig& serv)
{
    if (req.path.empty())
        return errorResponse(400, "", &serv);

    /*
     * req.path already comes normalized from dispatchRequest().
     */
    std::string cleanPath =
        normalizePath(req.path);

    LocationConfig loc =
        serv.matchLocation(cleanPath);

    if (loc.path.empty())
        return errorResponse(404, "", &serv);

    std::string target;
    std::string securityRoot;

    /*
     * Upload directory.
     */
    if (loc.allow_upload &&
        !loc.upload_path.empty())
    {
        std::string filename =
            cleanPath;

        size_t slash =
            filename.find_last_of('/');

        if (slash != std::string::npos)
        {
            filename =
                filename.substr(slash + 1);
        }

        if (filename.empty())
            return errorResponse(400, "", &serv);

        if (filename.find('/') != std::string::npos)
        {
            return errorResponse(
                403,
                "",
                &serv
            );
        }

        target = loc.upload_path;

        if (!target.empty() &&
            target[target.size() - 1] != '/')
        {
            target += '/';
        }

        target += filename;

        securityRoot =
            loc.upload_path;
    }
    else
    {
        target =
            buildPath(
                cleanPath,
                loc
            );

        securityRoot =
            loc.root;
    }

    /*
     * Prevent deleting outside root.
     */
    if (securityRoot.empty() ||
        !isInsideRoot(
            target,
            securityRoot))
    {
        return errorResponse(
            403,
            "",
            &serv
        );
    }

    if (!fileExists(target))
    {
        return errorResponse(
            404,
            "",
            &serv
        );
    }

    /*
     * Do not DELETE directories or symlinks.
     */
    if (isDirectory(target) ||
        isSymlink(target))
    {
        return errorResponse(
            403,
            "",
            &serv
        );
    }

    if (std::remove(target.c_str()) != 0)
    {
        if (errno == EACCES ||
            errno == EPERM)
        {
            return errorResponse(
                403,
                "",
                &serv
            );
        }

        if (errno == ENOENT)
        {
            return errorResponse(
                404,
                "",
                &serv
            );
        }

        return errorResponse(
            500,
            "",
            &serv
        );
    }

    return buildResponse(
        204,
        "",
        ""
    );
}


/*
 * ============================================================
 * PERCENT DECODING
 * ============================================================
 */

static int hexValue(char c)
{
    if (c >= '0' && c <= '9')
        return c - '0';

    if (c >= 'a' && c <= 'f')
        return c - 'a' + 10;

    if (c >= 'A' && c <= 'F')
        return c - 'A' + 10;

    return -1;
}


static bool percentDecode(
    const std::string& input,
    std::string& output)
{
    output.clear();

    for (size_t i = 0;
         i < input.size();
         ++i)
    {
        if (input[i] != '%')
        {
            output += input[i];
            continue;
        }

        /*
         * % must have 2 hex chars.
         */
        if (i + 2 >= input.size())
            return false;

        int high =
            hexValue(input[i + 1]);

        int low =
            hexValue(input[i + 2]);

        if (high == -1 ||
            low == -1)
        {
            return false;
        }

        char decoded =
            static_cast<char>(
                (high << 4) | low
            );

        /*
         * Reject encoded NUL.
         */
        if (decoded == '\0')
            return false;

        output += decoded;

        i += 2;
    }

    return true;
}


/*
 * ============================================================
 * DISPATCH
 * ============================================================
 */

std::string dispatchRequest(
    const HttpRequest& req,
    const ServerConfig& Serv)
{
    /*
     * 1. Malformed request line.
     */
    if (req.method.empty() ||
        req.path.empty() ||
        req.version.empty())
    {
        return attachSessionCookie(
            req,
            errorResponse(
                400,
                "",
                &Serv
            )
        );
    }

    /*
     * 2. HTTP/1.1 only.
     */
    if (req.version != "HTTP/1.1")
    {
        return attachSessionCookie(
            req,
            errorResponse(
                505,
                "",
                &Serv
            )
        );
    }

    /*
     * 3. Host required.
     */
    std::string host;

    if (!getHeaderValue(
            req,
            "Host",
            host) ||
        host.empty())
    {
        return attachSessionCookie(
            req,
            errorResponse(
                400,
                "",
                &Serv
            )
        );
    }

    /*
     * 4. Supported methods.
     */
    if (req.method != "GET" &&
        req.method != "POST" &&
        req.method != "DELETE" &&
        req.method != "HEAD")
    {
        return attachSessionCookie(
            req,
            errorResponse(
                501,
                "",
                &Serv
            )
        );
    }

    /*
     * 5. URI length.
     */
    if (req.path.size() > 8192 ||
        req.query_string.size() > 8192)
    {
        return attachSessionCookie(
            req,
            errorResponse(
                414,
                "",
                &Serv
            )
        );
    }

    /*
     * 6. Percent decode BEFORE resolving path.
     *
     * Example:
     *
     * /foo/%2e%2e%2fbar
     *
     * =>
     *
     * /foo/../bar
     */
    std::string decodedPath;

    if (!percentDecode(
            req.path,
            decodedPath))
    {
        return attachSessionCookie(
            req,
            errorResponse(
                400,
                "",
                &Serv
            )
        );
    }

    /*
     * 7. Normalize AFTER decoding.
     *
     * Raw:
     * /foo/../bar
     *
     * Encoded:
     * /foo/%2e%2e%2fbar
     *
     * Both become:
     * /bar
     *
     * IMPORTANT:
     * DO NOT return 403 just because
     * decodedPath contains "..".
     */
    std::string cleanPath =
        normalizePath(
            decodedPath
        );

    if (cleanPath.empty())
    {
        return attachSessionCookie(
            req,
            errorResponse(
                400,
                "",
                &Serv
            )
        );
    }

    /*
     * 8. Normalized URI length.
     */
    if (cleanPath.size() > 8192)
    {
        return attachSessionCookie(
            req,
            errorResponse(
                414,
                "",
                &Serv
            )
        );
    }

    /*
     * 9. Location matching.
     */
    LocationConfig loc =
        Serv.matchLocation(
            cleanPath
        );

    if (loc.path.empty())
    {
        return attachSessionCookie(
            req,
            errorResponse(
                404,
                "",
                &Serv
            )
        );
    }

    /*
     * 10. Internal location.
     */
    if (loc.internal)
    {
        return attachSessionCookie(
            req,
            errorResponse(
                404,
                "",
                &Serv
            )
        );
    }

    /*
     * 11. Redirect.
     */
    if (loc.redirect_code != 0)
    {
        return attachSessionCookie(
            req,
            redirectResponse(
                loc.redirect_code,
                loc.redirect
            )
        );
    }

    /*
     * 12. Root required.
     */
    if (loc.root.empty())
    {
        return attachSessionCookie(
            req,
            errorResponse(
                500,
                "",
                &Serv
            )
        );
    }

    /*
     * 13. Method restriction.
     */
    std::string allowHeader =
        buildAllowHeader(loc);

    if (!isMethodAllowed(
            loc,
            req.method))
    {
        return attachSessionCookie(
            req,
            errorResponse(
                405,
                allowHeader,
                &Serv
            )
        );
    }

    /*
     * 14. Build clean request.
     *
     * Everything after this receives
     * decoded + normalized path.
     */
    HttpRequest cleanReq = req;

    cleanReq.path = cleanPath;

    /*
     * Preserve trailing slash.
     */
    if (!decodedPath.empty() &&
        decodedPath[
            decodedPath.size() - 1
        ] == '/' &&
        cleanPath != "/" &&
        cleanPath[
            cleanPath.size() - 1
        ] != '/')
    {
        cleanReq.path += "/";
    }

    /*
     * 15. GET.
     */
    if (cleanReq.method == "GET" || cleanReq.method == "HEAD")
    {
        std::string response =
            handleRequest(
                cleanReq,
                loc,
                &Serv
            );

        return attachSessionCookie(
            req,
            response
        );
    }

    /*
     * 16. POST.
     */
    if (cleanReq.method == "POST")
    {
        std::string response =
            handlePOST(
                cleanReq,
                Serv
            );

        return attachSessionCookie(
            req,
            response
        );
    }

    /*
     * 17. DELETE.
     */
    if (cleanReq.method == "DELETE")
    {
        std::string response =
            handleDELETE(
                cleanReq,
                Serv
            );

        return attachSessionCookie(
            req,
            response
        );
    }

    /*
     * HEAD remains intentionally unsupported.
     */
    return attachSessionCookie(
        req,
        errorResponse(
            501,
            "",
            &Serv
        )
    );
}