server {
    listen 8080;
    server_name localhost;

    root www;

    index index.html;

    location / {
        root www;
        autoindex off;
    }

    location /images {
        root www/images;
        autoindex on;
    }

    location /upload {
        root www/upload;
        autoindex off;
    }
}